config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  root to: "users#index"
  
  resources :users, only: [:index, :show] do
    # Nested resourceful route for posts
    resources :posts, only: [:index, :show, :new, :create]
  end

  get '/users/:user_id/posts/:post_id/comments/new', to: 'comments#new', as: 'new_user_post_comment'
  post '/users/:user_id/posts/:post_id/comments', to: 'comments#create', as: 'user_post_comments'
  post '/users/:user_id/posts/:post_id/likes', to: 'likes#create', as: 'user_post_likes'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  has_many :posts, foreign_key: :user_id
  has_many :comments, foreign_key: :user_id
  has_many :likes

  validates :name, presence: true
  validates :post_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def three_most_recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::ApplicationController
  before_action :set_user, only: %i[show update destroy]

  def index
    @users = User.all

    render json: @users
  end

  def show
    render json: @user
  end

  def create
    @user = User.find(params[:id])

    if @user.save
      render json: @user, status: :created, location: @user
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      render json: @user
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  def show
    @user = User.includes(posts: :comments).find(params[:id])
    @three_most_recent_posts = @user.posts.order(created_at: :desc).limit(3)
  end
end

app/views/users/index.html.erb
<h1>Here is a List of all Users</h1>
<ul>
  <% @users.each do |user| %>
    <li id="user-card-<%= user.id %>">
      <div">
        <img src="<%= user.photo %>" alt="<%= user.name %>'s photo" width="100% heigth="100%">
      </div>
      <div>
        <h2><%= link_to user.name, user_path(user) %></h2>
        <p>Number of posts: <%= user.posts.count %></p>
      </div>
    </li>
  <% end %>
</ul>

<%= form_tag destroy_user_session_path, method: :delete, class: 'logout-form' do %>
  <%= submit_tag 'Log out', class: 'logout-button' %>
<% end %>

<a href="/users/1/posts/new">New Post</a>

app/views/users/recent_post.html.erb
<h1>Recent Posts for <%= @user.name %></h1>
<ul>
  <% @recent_posts.each do |post| %>
    <li><%= post.title %> - <%= post.created_at %></li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h1>User Information</h1>
<div class="user-card flex">
  <div class="user-image border">
    <img src="<%= @user.photo %>" alt="<%= @user.name %>'s photo" width="100%" height="100%">
  </div>
  <div class="user-info border">
    <h2><%= @user.name %></h2>
    <p class="posts-number">Number of posts: <%= @user.posts.count %></p>
  </div>
</div>
<div class="user-card left">
  <h3>Bio:</h3>
  <p><%= @user.bio %></p>
</div>
<div>
  <ul>
    <% @user.three_most_recent_posts.each do |post| %>
      <li class="user-card left">
        <h3><%= link_to post.title, user_post_path(@user, post) %></h3>
        <p><%= post.content %></p>
        <div class="right">
          <span class="span-post">Comments: <%= post.comments.count %></span>
          <span class="span-post" data-target="likes_count">Likes: <%= post.likes.count %></span>
        </div>
      </li>
    <% end %>
  </ul>
  <%= button_to "See All Posts", user_posts_path(@user), method: :get, class: "button" %>
</div>