config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  root to: "users#index"
  
  resources :users, only: [:index, :show] do
    # Nested resourceful route for posts
    resources :posts, only: [:index, :show, :new, :create]
  end

  get '/users/:user_id/posts/:post_id/comments/new', to: 'comments#new', as: 'new_user_post_comment'
  post '/users/:user_id/posts/:post_id/comments', to: 'comments#create', as: 'user_post_comments'
  post '/users/:user_id/posts/:post_id/likes', to: 'likes#create', as: 'user_post_likes'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: :user_id
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { maximum: 250 }
  validates :content, presence: true
  validates :comments_counter, :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_post_counter

  def five_most_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_post_counter
    user.update(post_counter: user.posts.count)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::V1::ApplicationController
  before_action :set_post, only: %i[show update destroy]

  def index
    @posts = Post.where(author_id: params[:user_id])

    render json: @posts, only: %i[title text]
  end

  def show
    render json: @post
  end

  def create
    @post = Post.find(params[:id])

    if @post.save
      render json: @post, status: :created, location: @post
    else
      render json: @post.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT
  def update
    if @post.update(post_params)
      render json: @post
    else
      render json: @post.errors, status: :unprocessable_entity
    end
  end

  # DELETE
  def destroy
    @post.destroy
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:text)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user
  before_action :load_posts, only: [:index]

  def index
    @posts = @user.posts.includes(:comments, :likes).page(params[:page]).per(3)
  end

  def create
    @post = @user.posts.build(post_params)
    @post.comments_counter = 0
    @post.likes_counter = 0
    if @post.save
      redirect_to user_post_path(@user, @post), notice: 'Post was successfully created.'
    else
      flash.now[:alert] = 'Post creation failed!'
      render :new
    end
  end

  def show
    @post = @user.posts.includes(:comments).find(params[:id])
    @next_post = @user.posts.where('id > ?', @post.id).first
    @prev_post = @user.posts.where('id < ?', @post.id).last
  end

  def new
    @post = @user.posts.build
  end

  private

  def find_user
    @user = User.find(params[:user_id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def load_posts
    @posts = @user.posts.includes(:comments, :likes).page(params[:page]).per(3)
  end
end

app/controllers/posts_controllers.rb
class PostsController < ApplicationController
  # Action for listing all posts by a user
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

  # Action for displaying a single post
  def show
    @post = Post.find(params[:id])
  end
end

app/views/posts/_comment_form.html.erb
<%= form_with(model: [post, Comment.new], url: user_post_comments_path(post.user, post), local: true) do |form| %>
    <!-- Form fields for adding a comment -->
    <%= form.text_area :content, placeholder: 'Your comment' %>
    <%= form.submit 'Add Comment' %>
  <% end %>
  

app/views/posts/_form.html.erb
<%= form_with(model: post, url: user_posts_path(@user)) do |form| %>
    <div>
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
  
    <div>
      <%= form.label :content %>
      <%= form.text_area :content %>
    </div>
  
    <div>
      <%= form.submit 'Create Post', class: 'button' %>
    </div>
  <% end %>
  

app/views/posts/_post_form.html.erb
<%= form_with(model: [current_user, Post.new]) do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>
  <%= form.submit 'Create Post' %>
<% end %>

app/views/posts/index.html.erb
<h1>All Posts</h1>
<div>
  <div>
    <div>
      <img src="<%= @user.photo %>" alt="<%= @user.name %>'s photo" width="100%" heigth="100%">
    </div>
    <div>
      <h2><%= @user.name %></h2>
      <p>Number of posts: <%= @user.posts.count %></p>
    </div>
  </div>
</div>

<% @posts.each do |post| %>
  <div>
    <h3><%= link_to post.title, user_post_path(@user, post) %></h3>
    <p><%= truncate(post.content, length: 100) %></p>
    <p>Number of comments: <%= post.comments.count %></p>
    <p>First comment: <%= post.comments.first.text if post.comments.first %></p>
    <p>Number of likes: <%= post.likes.count %></p>
  </div>
<% end %>

<%= paginate @posts, param_name: 'page', class: 'button' %>

app/views/posts/new.html.erb
<h2>New Post</h2>

<%= render 'form', post: @post %>

<%= link_to 'Back', user_posts_path(@user), class: 'button' %>

app/views/posts/show.html.erb
<h2>Post Show Page</h2>
<div>
  <div>
    <h3><%= @post.title %> by <%= @user.name %></h3>
    <p><%= @post.content %></p>
    <div>
      <span>Comments: <%= @post.comments.count %></span>
      <span data-target="likes_count">Likes: <%= @post.likes.count %></span>
      <%= button_to "Like", user_post_likes_path(@user, @post), method: :post, class: "button", remote: true %>
    </div>
    <br>
  </div>
  <div>
    <ul>
      <h5>All the Comments:</h5>
      <br>
      <% @post.comments.each do |comment| %>
        <li><%= comment.user.name %>: <%= comment.text %></li>
      <% end %>
    </ul>
  </div>
</div>

<%= link_to 'New Comment', new_user_post_comment_path(@user, @post) %>

<% if @prev_post.present? %>
  <%= button_to "Previous Post", user_post_path(@user, @prev_post), method: :get %>
<% end %>

<% if @next_post.present? %>
  <%= button_to "Next Post", user_post_path(@user, @next_post), method: :get %>
<% end %>